from pathlib import Path

# Folder Names
CSV_FOLDER_NAME = "csv"
HTML_FOLDER_NAME = "html"

# Folder Paths
PROJECT_ROOT_PATH = Path(__file__).parents[0] / Path("..")
CSV_FOLER_PATH = PROJECT_ROOT_PATH / CSV_FOLDER_NAME
HTML_FOLER_PATH = PROJECT_ROOT_PATH / HTML_FOLDER_NAME

# File Names
COVID_PAGE_NAME = "page.html"
OUTPUT_FILE_NAME = "output.csv"
BUILDING_CODE_MAP_NAME = "building_code_map.csv"
CLASS_DIR_PAGE_NAME = "building_directory.html"

# File Paths
COVID_PAGE_PATH = HTML_FOLER_PATH / COVID_PAGE_NAME
OUTPUT_FILE_PATH = PROJECT_ROOT_PATH / OUTPUT_FILE_NAME
BUILDING_CODE_MAP_PATH = CSV_FOLER_PATH / BUILDING_CODE_MAP_NAME
CLASS_DIR_PAGE_PATH = HTML_FOLER_PATH / CLASS_DIR_PAGE_NAME

QUIET_MODE = False